name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
          username: "administrator"
          host: "cornrester.ddns.net"
          password: "Ballat26215"
          script: 'RUN_YPUR_DEPLOYMENT_SCRIPT' #cd C:\inetpub\wwwroot\bbs&& ./deploy.bat