name: bbs

on:
  push:
    branches:
      - master  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4  # Change this to the PHP version you want to use

      - name: Install Composer
        run: |
            Invoke-WebRequest -Uri 'https://getcomposer.org/installer' -OutFile 'composer-setup.php'
            php composer-setup.php
            rm composer-setup.php
            Move-Item -Path .\composer.phar -Destination C:\ProgramData\ComposerSetup\bin\composer.exe

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy to server
        run: |
          # Add your deployment commands here
