name: Auto Deploy Laravel

on:
  push:
    branches:
<<<<<<< HEAD
      - main  # Change this to the branch you want to deploy from
=======
      - master  # Change this to the branch you want to deploy from
>>>>>>> 1ebebcaf8af9d44582aa4898592588776d6e4958

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4  # Change this to the PHP version you want to use

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          mv composer.phar C:\ProgramData\ComposerSetup\bin\

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy to server
        run: |
<<<<<<< HEAD
          # Add your deployment commands here
=======
          # Add your deployment commands here
>>>>>>> 1ebebcaf8af9d44582aa4898592588776d6e4958
